@host = http://localhost:5262

Get {{host}}/client
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZDkxZGNiNS02OWZmLTQ5MGUtOWFlMS00MWQxNmIzYzc5OGIiLCJnaXZlbl9uYW1lIjoibW9oYW1lZCIsImZhbWlseV9uYW1lIjoiQWxpIiwianRpIjoiMWM5YjEzMmMtYjNlZS00NmE1LWI2ZTgtZWViOGU2ZmNkZDFmIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3MjQyODEzMzksImlzcyI6Ik9BdXRoIiwiYXVkIjoiQmFua2luZyJ9.8Atqc6asESfjv0NiEP_fS50Q4odkT24b1nA3o7FAtTo